version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - postgres
    command: >
      sh -c "npm start"
    volumes:
      - ./backend:/app # Mount the backend directory into the container

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "!Mohal6889"
      POSTGRES_DB: "taratalent"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
