export enum ServiceLeveEnum {
  Junior = "Junior",
  Mid = "Mid-Level",
  Senior = "Senior",
}

export enum ServiceEnum {
  Web = "Web Development",
  Mobile = "Mobile Development",
  QA = "Quality Assurance",
  AI = "Machine Learning",
  UX = "UI/UX Design",
  Art = "Building Architecture",
  Devops = "Devops",
}

export const services = [
  {
    name: ServiceEnum.Web,
    dev: "Web Developer",
    value: "web",
    selected: true,
    index: 0,
    technologies: [
      "React",
      "Angular",
      "Vue",
      "C#",
      "Python",
      "Nodejs",
      "Nestjs",
      "Nextjs",
      "AWS",
      "Google Cloud",
    ],
    start: 23,
    end: 50,
  },
  {
    name: ServiceEnum.Mobile,
    dev: "Mobile Developer",
    value: "mobile",
    selected: false,
    index: 1,
    technologies: ["IOS", "Android", "Kotlin", "swift", "Java"],
    start: 25,
    end: 46,
  },
  {
    name: ServiceEnum.QA,
    dev: "QA Specialist",
    value: "qa",
    selected: false,
    index: 4,
    technologies: [
      "Unit Testing",
      "Integration Testing",
      "Acceptance Testing",
      "Black Box Testing",
      "White Box Testing",
    ],
    start: 21,
    end: 42,
  },
  {
    name: ServiceEnum.AI,
    dev: "AI Engineer",
    value: "ai",
    selected: false,
    index: 6,
    technologies: [
      "Computer Vision (CV) Engineer",
      "Natural Language Processing (NLP) Specialist",
      "Machine Learning Operations (MLOps) Engineer",
      "Data Science and Analytics",
      "AI Research Scientist",
    ],
    start: 22,
    end: 50,
  },
  {
    name: ServiceEnum.UX,
    dev: "UI Designer",
    value: "ui",
    selected: false,
    index: 2,
    technologies: [
      "UI/UX Designer",
      "Product Designer",
      "UX Researcher",
      "Interaction Designer",
      "Visual Designer",
    ],
    start: 24,
    end: 40,
  },
  {
    name: ServiceEnum.Art,
    dev: "Art Designer",
    value: "art",
    selected: false,
    index: 3,
    technologies: [
      "Architectural Designer",
      "BIM Engineer",
      "Architectural Visualizer",
      "Energy and Sustainability Consultant",
      "Vector Graphics",
      "CAD Technician",
      "3D Modeling Specialist",
    ],
    start: 35,
    end: 45,
  },

  {
    name: ServiceEnum.Devops,
    dev: "Devops Engineer",
    value: "devops",
    selected: false,
    index: 5,
    technologies: [
      "DevOps Engineer",
      "Site Reliability Engineer (SRE)",
      "Cloud Engineer",
      "Security Specialist",
      "System Admin",
      "Platform Engineer",
    ],
    start: 27,
    end: 49,
  },
];
