export enum ServiceLeveEnum {
  Junior = "Junior",
  Mid = "Mid-Level",
  Senior = "Senior",
}

export enum ServiceEnum {
  Web = "Web Development",
  Mobile = "Mobile Development",
  QA = "Software testing",
  AI = "Machine Learning",
  UX = "UI/UX Design",
  Art = "Digital Art",
  Devops = "Devops",
}

export const services = [
  {
    name: ServiceEnum.Web,
    dev: "Web Developer",
    value: "web",
    selected: true,
    index: 0,
    technologies: [
      "React",
      "Angular",
      "Vue",
      "C#",
      "Python",
      "Nodejs",
      "Nestjs",
      "Nextjs",
      "AWS",
      "Google Cloud",
    ],
    start: 53,
    end: 82,
  },
  {
    name: ServiceEnum.Mobile,
    dev: "Mobile Developer",
    value: "mobile",
    selected: false,
    index: 1,
    technologies: ["IOS", "Android", "Kotlin", "swift", "Java"],
    start: 55,
    end: 76,
  },
  {
    name: ServiceEnum.QA,
    dev: "QA Specialist",
    value: "qa",
    selected: false,
    index: 4,
    technologies: [
      "Unit Testing",
      "Integration Testing",
      "Acceptance Testing",
      "Black Box Testing",
      "White Box Testing",
    ],
    start: 51,
    end: 72,
  },
  {
    name: ServiceEnum.AI,
    dev: "AI Engineer",
    value: "ai",
    selected: false,
    index: 6,
    technologies: [
      "Narrow AI",
      "Deep Learning",
      "Neural Networks",
      "General AI",
      "Superintelligent AI",
    ],
    start: 62,
    end: 83,
  },
  {
    name: ServiceEnum.UX,
    dev: "UI Designer",
    value: "ui",
    selected: false,
    index: 2,
    technologies: ["Figma", "Adobe XD", "Adobe Illustrator", "Photoshop"],
    start: 48,
    end: 70,
  },
  {
    name: ServiceEnum.Art,
    dev: "Art Designer",
    value: "art",
    selected: false,
    index: 3,
    technologies: [
      "Blender",
      "Adobe Creative Suite",
      "2D and 3D Animation",
      "Motion Graphics",
      "Vector Graphics",
      "2D and 3D Digital Painting",
      "Digital Photography ",
    ],
    start: 45,
    end: 59,
  },

  {
    name: ServiceEnum.Devops,
    dev: "Devops Engineer",
    value: "devops",
    selected: false,
    index: 5,
    technologies: [
      "CI/CD",
      "Git",
      "AWS",
      "Bash/Shel scripting",
      "VMware",
      "NGinx",
    ],
    start: 57,
    end: 79,
  },
];
